### ISSUE TITLE
Cmake can't find the SFML Package (Mac OS)

### ISSUE THREAD

**Issue by Platinum-Phoenix** [Fenex330/Survivio#1]
Error message:
```
CMake Warning at CMakeLists.txt:27 (find_package):
  By not providing "FindSFML.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SFML", but
  CMake did not find one.

  Could not find a package configuration file provided by "SFML" (requested
  version 2.5.1) with any of the following names:

    SFMLConfig.cmake
    sfml-config.cmake

  Add the installation prefix of "SFML" to CMAKE_PREFIX_PATH or set
  "SFML_DIR" to a directory containing one of the above files.  If "SFML"
  provides a separate development package or SDK, be sure it has been
  installed.
```

System: 
Macbook Air
MacOS Catalina 10.15.6
CMake 3.18.2

**Comment by Platinum-Phoenix** [comment]
Also for the sprites file you can use the [survivio-creator-kit](https://drive.google.com/drive/folders/1qhaDdNCsisBu_7gvMNmyn_zkG4kyAZix?usp=sharing) it most of the game sprites and buildings :D.

**Comment by Fenex330** [comment]
@Platinum-Phoenix I think I fixed the first part of the error by removing useless status logs, the second one is mac os specific, will be fixed soon, but takes more time. And thanks for the creator kit. :))

**Comment by Platinum-Phoenix** [comment]
Yea. No problem.

**Comment by Platinum-Phoenix** [comment]
#2 will fix it
