### ISSUE TITLE
Problem Building

### ISSUE THREAD

**Issue by kingmanas** [Fenex330/Survivio#9]
`cmake -G"Ninja" -DCMAKE_BUILD_TYPE="Debug"  .` gives the following error:

```
CMake Error at CMakeLists.txt:11 (message):
  FATAL: In-source builds are not allowed.  You should create a separate
  directory for build files.


-- Configuring incomplete, errors occurred!
```

**Comment by Fenex330** [comment]
Follow the instructions in README.md and create a separate "build" folder to build the project there

**Comment by kingmanas** [comment]
Did exactly what is mentioned.
1. Cloned Survivio
2. cd Survivio
3. mkdir build
4. cd build
5. cmake .. && cmake --build

Then I saw you made a dev-build.sh but it gave the error mentioned earlier

**Comment by Fenex330** [comment]
@kingmanas That's weird, try to clean the build directory from cmake cache (delete and create again with mkdir) first.
Also, you should execute the dev-build.sh script from Survivio/ directory, not from build/ one
At least, does the normal "cmake .. && cmake --build" command work?

**Comment by kingmanas** [comment]
@Fenex330 Deleting the CMakeCache.txt and then running `dev-build.sh` solved the issue
